project_name: handson-grpc-go
builds:
  - id: "handson-grpc-go"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 5
      - 6
      - 7
    dir: .
    main: ./main.go
    binary: handson-grpc-go
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/ks6088ts/handson-grpc-go/internal.Revision={{.Commit}}'
      - -X 'github.com/ks6088ts/handson-grpc-go/internal.Version={{.Version}}'
release:
  draft: true
archives:
  - wrap_in_directory: true
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
